In [1]:
# Verivikasi Versi Library

In [2]:
# Cek versi library
import sys
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

print("Python      :", sys.version.split()[0])
print("pandas      :", pd.__version__)
print("numpy       :", np.__version__)
print("matplotlib  :", matplotlib.__version__)

Python      : 3.10.20
pandas      : 2.3.3
numpy       : 2.2.5
matplotlib  : 3.10.9

In [3]:
# Variabel dan tipe data dasar

In [4]:
nama_mahasiswa = "Budi"         # string (teks)
npm = 210411001                 # integer (bilangan bulat)
ipk = 3.75                      # float (bilangan desimal)
aktif_kuliah = True             # boolean (benar/salah)

print(f"Nama       : {nama_mahasiswa} ({type(nama_mahasiswa).__name__})")
print(f"NPM        : {npm} ({type(npm).__name__})")
print(f"IPK        : {ipk} ({type(ipk).__name__})")
print(f"Aktif      : {aktif_kuliah} ({type(aktif_kuliah).__name__})")

Nama       : Budi (str)
NPM        : 210411001 (int)
IPK        : 3.75 (float)
Aktif      : True (bool)

In [5]:
daftar_nilai = [85, 90, 78, 92, 88]   # list: kumpulan nilai terurut
print("Daftar nilai:", daftar_nilai)
print("Rata-rata   :", sum(daftar_nilai) / len(daftar_nilai))

mahasiswa = {                          # dictionary: pasangan key-value
    "nama": "Budi",
    "npm": 210411001,
    "jurusan": "Teknologi Informasi",
    "semester": 3
}
print("\nData mahasiswa:")
for key, value in mahasiswa.items():
    print(f"  {key}: {value}")

Daftar nilai: [85, 90, 78, 92, 88]
Rata-rata   : 86.6

Data mahasiswa:
  nama: Budi
  npm: 210411001
  jurusan: Teknologi Informasi
  semester: 3

In [6]:
# Membuat dan Mengeksplorasi dengan pandas

In [7]:
# Membuat DataFrame dari dictionary
# Studi kasus: data penjualan mingguan sebuah UMKM di beberapa kota

data_penjualan = {
    "kota": ["Magelang", "Yogyakarta", "Semarang", "Solo", "Magelang", "Yogyakarta", "Semarang", "Solo"],
    "minggu": [1, 1, 1, 1, 2, 2, 2, 2],
    "produk": ["Kaos", "Kaos", "Kaos", "Kaos", "Kaos", "Kaos", "Kaos", "Kaos"],
    "unit_terjual": [120, 95, 150, 80, 135, 110, 160, 90],
    "harga_satuan": [75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000]
}

df = pd.DataFrame(data_penjualan)
df

         kota  minggu produk  unit_terjual  harga_satuan
0    Magelang       1   Kaos           120         75000
1  Yogyakarta       1   Kaos            95         75000
2    Semarang       1   Kaos           150         75000
3        Solo       1   Kaos            80         75000
4    Magelang       2   Kaos           135         75000
5  Yogyakarta       2   Kaos           110         75000
6    Semarang       2   Kaos           160         75000
7        Solo       2   Kaos            90         75000

In [8]:
# Melihat 5 baris pertama
df.head()

# Informasi struktur data: jumlah baris, tipe data tiap kolom, dan
# memori yang digunakan.
df.info()

# Ringkasan statistik deskriptif untuk kolom numerik.
df.describe()

# Menambahkan kolom baru hasil perhitungan:
# total pendapatan = unit_terjual x harga_satuan
df["total_pendapatan"] = df["unit_terjual"] * df["harga_satuan"]
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   kota          8 non-null      object
 1   minggu        8 non-null      int64
 2   produk        8 non-null      object
 3   unit_terjual  8 non-null      int64
 4   harga_satuan  8 non-null      int64
dtypes: int64(3), object(2)
memory usage: 448.0+ bytes

         kota  minggu produk  unit_terjual  harga_satuan  total_pendapatan
0    Magelang       1   Kaos           120         75000           9000000
1  Yogyakarta       1   Kaos            95         75000           7125000
2    Semarang       1   Kaos           150         75000          11250000
3        Solo       1   Kaos            80         75000           6000000
4    Magelang       2   Kaos           135         75000          10125000
5  Yogyakarta       2   Kaos           110         75000           8250000
6    Semarang       2   Kaos           160         75000          12000000
7        Solo       2   Kaos            90         75000           6750000

In [9]:
# Filtering and Group by

In [10]:
# Filtering: menampilkan hanya data dari kota Magelang
data_magelang = df[df["kota"] == "Magelang"]
data_magelang

       kota  minggu produk  unit_terjual  harga_satuan  total_pendapatan
0  Magelang       1   Kaos           120         75000           9000000
4  Magelang       2   Kaos           135         75000          10125000

In [11]:
# Filtering dengan lebih dari satu kondisi:
# tampilkan data dengan unit_terjual lebih dari 100 DAN minggu ke-2
data_filter = df[(df["unit_terjual"] > 100) & (df["minggu"] == 2)]
data_filter

         kota  minggu produk  unit_terjual  harga_satuan  total_pendapatan
4    Magelang       2   Kaos           135         75000          10125000
5  Yogyakarta       2   Kaos           110         75000           8250000
6    Semarang       2   Kaos           160         75000          12000000

In [12]:
# Group by: total pendapatan per kota (menjumlahkan data minggu 1 dan minggu 2)
total_per_kota = df.groupby("kota")["total_pendapatan"].sum().sort_values(ascending=False)
print("Total pendapatan per kota (2 minggu):")
total_per_kota

Total pendapatan per kota (2 minggu):

kota
Semarang      23250000
Magelang      19125000
Yogyakarta    15375000
Solo          12750000
Name: total_pendapatan, dtype: int64

In [13]:
# Soal 1. Buat data frame baru yang bernama df_nilai yang isinya nilai 5 Mahasiswa (kolom: Nama, UTS, UAS).
# Tambah juga nilai_akhir dari (UTS * 0.4) + (UAS * 0.6).

In [14]:
# 1. Inisiasi (dictionary).
data_mahasiswa = {
    "nama": ["Stein", "Rey", "Caitly", "Neo", "Nerro"],
    "uts": [85, 75, 90, 60, 88],
    "uas": [80, 85, 85, 70, 92]
}

# 2. Membuat DataFrame.
df_nilai = pd.DataFrame(data_mahasiswa)

# 3. Menambahkan kolom nilai_akhir.
df_nilai["nilai_akhir"] = (df_nilai["uts"] * 0.4) + (df_nilai["uas"] * 0.6)

# Menampilkan DataFrame.
df_nilai

     nama  uts  uas  nilai_akhir
0   Stein   85   80         82.0
1     Rey   75   85         81.0
2  Caitly   90   85         87.0
3     Neo   60   70         66.0
4   Nerro   88   92         90.4

In [15]:
# Soal 2. Tampilkan nama Mahasiswa yang nilainya > 80 saja.

In [16]:
# Memfilter data dengan kondisi nilai_akhir di atas 80
mahasiswa_lulus = df_nilai[df_nilai["nilai_akhir"] > 80]

# Menampilkan hasil filter
mahasiswa_lulus

     nama  uts  uas  nilai_akhir
0   Stein   85   80         82.0
1     Rey   75   85         81.0
2  Caitly   90   85         87.0
4   Nerro   88   92         90.4